// src/views/configFormHtml.ts
// 生成插件配置 webview 的完整 HTML(含内联 <style> + <script>)。
// 主题跟随 VS Code:全部用 --vscode-* CSS 变量,不写死颜色。
// 表单渲染逻辑按 AstrBot 自定义 schema 格式(见 design.md §4.3 / skill-astrbot-dev/plugin_config/schema.md)。

import type { ConfigSchema, SchemaField } from '../api/plugins.js';

/** 生成 webview HTML 字符串 */
export function configFormHtml(opts: {
    pluginName: string;
    pluginId: string;
    config: Record<string, unknown>;
    schema: ConfigSchema;
    nonce: string;       // <script nonce> 用,与 CSP 配套
    cspSource: string;   // panel.webview.cspSource
}): string {
    // 初始数据以 JSON 注入到 window.__INITIAL__;${} 转义由 JSON.stringify 兜底
    const initial = JSON.stringify({
        pluginName: opts.pluginName,
        pluginId: opts.pluginId,
        config: opts.config,
        schema: opts.schema,
    });
    return [
        '<!DOCTYPE html>',
        '<html lang="zh-CN">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta http-equiv="Content-Security-Policy" content="' +
            'default-src \'none\'; ' +
            'style-src \'unsafe-inline\'; ' +
            'script-src \'nonce-' + opts.nonce + '\';' +
        '">',
        '<style>', FORM_STYLE, '</style>',
        '</head>',
        '<body>',
        '<div id="header">',
        '  <h1 id="title"></h1>',
        '  <button id="rawJsonBtn" class="link-btn" type="button">改用原始 JSON 编辑</button>',
        '</div>',
        '<div id="error-bar" class="hidden"></div>',
        '<form id="form"></form>',
        '<div id="footer">',
        '  <button id="saveBtn" class="primary" type="button">保存到服务器</button>',
        '  <span id="status"></span>',
        '</div>',
        '<script nonce="' + opts.nonce + '">',
        'window.__INITIAL__ = ' + initial + ';',
        FORM_SCRIPT,
        '</script>',
        '</body>',
        '</html>',
    ].join('\n');
}

// ─── 内联脚本 ─────────────────────────────────────────────
// 注意:此字符串内不得出现 ${}(会被外层模板字面量误解析)。一律用字符串拼接。

const FORM_SCRIPT = [
    '(function () {',
    '  var init = window.__INITIAL__;',
    '  var schema = init.schema;',
    '  var model = init.config && typeof init.config === "object" ? init.config : {};',
    '  var titleEl = document.getElementById("title");',
    '  var formEl = document.getElementById("form");',
    '  var errorBar = document.getElementById("error-bar");',
    '  var statusEl = document.getElementById("status");',
    '  var saveBtn = document.getElementById("saveBtn");',
    '  var rawBtn = document.getElementById("rawJsonBtn");',
    '',
    '  titleEl.textContent = "插件配置 \\u00b7 " + init.pluginName;',
    '',
    '  // 渲染:顶层是 object(map),逐字段产出',
    '  renderObject(schema, model, formEl, "");',
    '',
    '  saveBtn.addEventListener("click", function () {',
    '    statusEl.textContent = "保存中\\u2026";',
    '    statusEl.className = "";',
    '    errorBar.className = "hidden";',
    '    clearErrors();',
    '    var value = collectObject(schema, model, "");',
    '    window.parent.postMessage({ type: "save", value: value }, "*");',
    '  });',
    '',
    '  rawBtn.addEventListener("click", function () {',
    '    window.parent.postMessage({ type: "editRawJson" }, "*");',
    '  });',
    '',
    '  window.addEventListener("message", function (ev) {',
    '    var msg = ev.data;',
    '    if (!msg || typeof msg !== "object") { return; }',
    '    if (msg.type === "errors") {',
    '      statusEl.textContent = "";',
    '      showErrors(msg.errors || []);',
    '    } else if (msg.type === "saved") {',
    '      statusEl.textContent = "\\u2705 已保存";',
    '      statusEl.className = "ok";',
    '    } else if (msg.type === "error") {',
    '      statusEl.textContent = "";',
    '      showErrorBar(msg.message || "保存失败");',
    '    }',
    '  });',
    '',
    '  // ── 渲染:object(map) → 逐字段 ──',
    '  function renderObject(subSchema, subModel, container, pathPrefix) {',
    '    Object.keys(subSchema).forEach(function (key) {',
    '      var field = subSchema[key];',
    '      if (field.invisible) { return; }',
    '      var path = pathPrefix ? pathPrefix + "." + key : key;',
    '      var raw = subModel && Object.prototype.hasOwnProperty.call(subModel, key)',
    '        ? subModel[key] : field.default;',
    '      renderField(field, key, raw, container, path);',
    '    });',
    '  }',
    '',
    '  // ── 渲染:单字段 → 行容器 + 控件 ──',
    '  function renderField(field, label, raw, container, path) {',
    '    var row = document.createElement("div");',
    '    row.className = "field";',
    '    row.setAttribute("data-path", path);',
    '',
    '    var lab = document.createElement("label");',
    '    lab.className = "field-label";',
    '    lab.textContent = label;',
    '    row.appendChild(lab);',
    '',
    '    if (field.description) {',
    '      var desc = document.createElement("div");',
    '      desc.className = "field-desc";',
    '      desc.textContent = field.description;',
    '      row.appendChild(desc);',
    '    }',
    '',
    '    var ctrl = document.createElement("div");',
    '    ctrl.className = "field-ctrl";',
    '    var t = (field.type || "").toLowerCase();',
    '    var hint = field.hint || (field.obvious_hint ? "" : "");',
    '',
    '    // _special / file / template_list / editor_*:降级只读占位',
    '    if (field._special || t === "file" || t === "template_list" || field.editor_mode || field.editor_language) {',
    '      renderPlaceholder(ctrl, raw, "此字段请用「原始 JSON 编辑」修改");',
    '    } else if (t === "bool") {',
    '      renderBool(ctrl, raw, path);',
    '    } else if (t === "int" || t === "float") {',
    '      renderNumber(ctrl, raw, field, path, t === "int");',
    '    } else if (t === "text") {',
    '      renderText(ctrl, raw, path, true, hint);',
    '    } else if (t === "string") {',
    '      if (field.options && field.options.length) {',
    '        renderSelect(ctrl, raw, field.options, path);',
    '      } else {',
    '        renderText(ctrl, raw, path, false, hint);',
    '      }',
    '    } else if (t === "list") {',
    '      renderList(ctrl, raw, field, path);',
    '    } else if (t === "object" || t === "dict") {',
    '      renderObjectGroup(ctrl, raw, field, path);',
    '    } else {',
    '      // 未知类型:文本兜底',
    '      renderText(ctrl, raw, path, false, hint);',
    '    }',
    '',
    '    row.appendChild(ctrl);',
    '    container.appendChild(row);',
    '  }',
    '',
    '  function renderBool(ctrl, raw, path) {',
    '    var cb = document.createElement("input");',
    '    cb.type = "checkbox";',
    '    cb.className = "ctrl-bool";',
    '    cb.checked = !!raw;',
    '    cb.setAttribute("data-path", path);',
    '    cb.setAttribute("data-kind", "bool");',
    '    ctrl.appendChild(cb);',
    '  }',
    '',
    '  function renderNumber(ctrl, raw, field, path, isInt) {',
    '    // slider:{min,max,step} 存在时用 range',
    '    if (field.slider && typeof field.slider.min === "number") {',
    '      var wrap = document.createElement("div");',
    '      wrap.className = "slider-wrap";',
    '      var r = document.createElement("input");',
    '      r.type = "range";',
    '      r.className = "ctrl-range";',
    '      r.setAttribute("data-path", path);',
    '      r.setAttribute("data-kind", isInt ? "int" : "float");',
    '      if (typeof field.slider.min === "number") { r.min = field.slider.min; }',
    '      if (typeof field.slider.max === "number") { r.max = field.slider.max; }',
    '      if (typeof field.slider.step === "number") { r.step = field.slider.step; }',
    '      else { r.step = isInt ? "1" : "any"; }',
    '      r.value = typeof raw === "number" ? raw : (field.default || 0);',
    '      var out = document.createElement("span");',
    '      out.className = "slider-val";',
    '      out.textContent = String(r.value);',
    '      r.addEventListener("input", function () { out.textContent = r.value; });',
    '      wrap.appendChild(r);',
    '      wrap.appendChild(out);',
    '      ctrl.appendChild(wrap);',
    '      return;',
    '    }',
    '    var inp = document.createElement("input");',
    '    inp.type = "number";',
    '    inp.className = "ctrl-number";',
    '    inp.setAttribute("data-path", path);',
    '    inp.setAttribute("data-kind", isInt ? "int" : "float");',
    '    inp.step = isInt ? "1" : "any";',
    '    if (typeof raw === "number") { inp.value = String(raw); }',
    '    else if (raw !== undefined && raw !== null) { inp.value = String(raw); }',
    '    ctrl.appendChild(inp);',
    '  }',
    '',
    '  function renderText(ctrl, raw, path, multiline, hint) {',
    '    var inp;',
    '    if (multiline) {',
    '      inp = document.createElement("textarea");',
    '      inp.rows = 3;',
    '      inp.className = "ctrl-textarea";',
    '    } else {',
    '      inp = document.createElement("input");',
    '      inp.type = "text";',
    '      inp.className = "ctrl-text";',
    '    }',
    '    inp.setAttribute("data-path", path);',
    '    inp.setAttribute("data-kind", "string");',
    '    inp.value = raw === undefined || raw === null ? "" : String(raw);',
    '    if (hint) { inp.placeholder = hint; }',
    '    ctrl.appendChild(inp);',
    '  }',
    '',
    '  function renderSelect(ctrl, raw, options, path) {',
    '    var sel = document.createElement("select");',
    '    sel.className = "ctrl-select";',
    '    sel.setAttribute("data-path", path);',
    '    sel.setAttribute("data-kind", "string");',
    '    var cur = raw === undefined || raw === null ? "" : raw;',
    '    options.forEach(function (opt) {',
    '      var o = document.createElement("option");',
    '      o.value = String(opt);',
    '      o.textContent = String(opt);',
    '      if (String(opt) === String(cur)) { o.selected = true; }',
    '      sel.appendChild(o);',
    '    });',
    '    ctrl.appendChild(sel);',
    '  }',
    '',
    '  // list:元素为基础类型时逐项输入;复杂元素降级占位',
    '  function renderList(ctrl, raw, field, path) {',
    '    var arr = Array.isArray(raw) ? raw.slice() : (Array.isArray(field.default) ? field.default.slice() : []);',
    '    var itemSchema = field.items || { type: "string" };',
    '    var itemT = (itemSchema.type || "string").toLowerCase();',
    '    var complex = itemT === "object" || itemT === "dict" || itemT === "list" ||',
    '      itemT === "file" || itemT === "template_list" || itemSchema._special;',
    '',
    '    var listEl = document.createElement("div");',
    '    listEl.className = "ctrl-list";',
    '    listEl.setAttribute("data-path", path);',
    '    listEl.setAttribute("data-kind", "list");',
    '    listEl.setAttribute("data-item-type", itemT);',
    '    listEl.setAttribute("data-complex", complex ? "1" : "0");',
    '',
    '    function addItem(val) {',
    '      var itemRow = document.createElement("div");',
    '      itemRow.className = "list-item";',
    '      if (complex) {',
    '        var ta = document.createElement("textarea");',
    '        ta.className = "ctrl-textarea list-item-json";',
    '        ta.rows = 2;',
    '        ta.value = val === undefined || val === null ? "" : (typeof val === "string" ? val : JSON.stringify(val));',
    '        itemRow.appendChild(ta);',
    '      } else if (itemT === "bool") {',
    '        var cb = document.createElement("input");',
    '        cb.type = "checkbox";',
    '        cb.className = "ctrl-bool";',
    '        cb.checked = !!val;',
    '        itemRow.appendChild(cb);',
    '      } else if (itemT === "int" || itemT === "float") {',
    '        var ni = document.createElement("input");',
    '        ni.type = "number";',
    '        ni.step = itemT === "int" ? "1" : "any";',
    '        ni.className = "ctrl-number";',
    '        if (typeof val === "number") { ni.value = String(val); }',
    '        else if (val !== undefined && val !== null) { ni.value = String(val); }',
    '        itemRow.appendChild(ni);',
    '      } else if (itemSchema.options && itemSchema.options.length) {',
    '        var sel = document.createElement("select");',
    '        sel.className = "ctrl-select";',
    '        itemSchema.options.forEach(function (opt) {',
    '          var o = document.createElement("option");',
    '          o.value = String(opt); o.textContent = String(opt);',
    '          if (String(opt) === String(val)) { o.selected = true; }',
    '          sel.appendChild(o);',
    '        });',
    '        itemRow.appendChild(sel);',
    '      } else {',
    '        var ti = document.createElement("input");',
    '        ti.type = "text";',
    '        ti.className = "ctrl-text";',
    '        ti.value = val === undefined || val === null ? "" : String(val);',
    '        itemRow.appendChild(ti);',
    '      }',
    '      var rm = document.createElement("button");',
    '      rm.type = "button";',
    '      rm.className = "icon-btn";',
    '      rm.textContent = "\\u2715";',
    '      rm.title = "删除该项";',
    '      rm.addEventListener("click", function () { itemRow.remove(); });',
    '      itemRow.appendChild(rm);',
    '      listEl.appendChild(itemRow);',
    '    }',
    '',
    '    arr.forEach(addItem);',
    '',
    '    var addBtn = document.createElement("button");',
    '    addBtn.type = "button";',
    '    addBtn.className = "ghost-btn";',
    '    addBtn.textContent = "+ 添加一项";',
    '    addBtn.addEventListener("click", function () {',
    '      addItem(itemSchema.default !== undefined ? itemSchema.default : null);',
    '    });',
    '    listEl.appendChild(addBtn);',
    '',
    '    ctrl.appendChild(listEl);',
    '  }',
    '',
    '  // object 分组:嵌套递归',
    '  function renderObjectGroup(ctrl, raw, field, path) {',
    '    var group = document.createElement("div");',
    '    group.className = "ctrl-object";',
    '    group.setAttribute("data-path", path);',
    '    group.setAttribute("data-kind", "object");',
    '    var subSchema = field.items || {};',
    '    var subModel = (raw && typeof raw === "object" && !Array.isArray(raw)) ? raw : {};',
    '    renderObject(subSchema, subModel, group, path);',
    '    ctrl.appendChild(group);',
    '  }',
    '',
    '  function renderPlaceholder(ctrl, raw, msg) {',
    '    var box = document.createElement("div");',
    '    box.className = "placeholder";',
    '    var val = document.createElement("input");',
    '    val.type = "text";',
    '    val.className = "ctrl-text";',
    '    val.readOnly = true;',
    '    val.value = raw === undefined || raw === null ? "" : (typeof raw === "object" ? JSON.stringify(raw) : String(raw));',
    '    box.appendChild(val);',
    '    var tip = document.createElement("div");',
    '    tip.className = "placeholder-tip";',
    '    tip.textContent = msg;',
    '    box.appendChild(tip);',
    '    ctrl.appendChild(box);',
    '  }',
    '',
    '  // ── 收集:object(map) → 普通 JS 对象 ──',
    '  function collectObject(subSchema, subModel, pathPrefix) {',
    '    var out = {};',
    '    Object.keys(subSchema).forEach(function (key) {',
    '      var field = subSchema[key];',
    '      // invisible / placeholder:原样回传,保留服务器既有值',
    '      var path = pathPrefix ? pathPrefix + "." + key : key;',
    '      if (field.invisible || field._special || (field.type || "").toLowerCase() === "file" ||',
    '          (field.type || "").toLowerCase() === "template_list" || field.editor_mode || field.editor_language) {',
    '        var raw = subModel && Object.prototype.hasOwnProperty.call(subModel, key)',
    '          ? subModel[key] : field.default;',
    '        out[key] = raw;',
    '        return;',
    '      }',
    '      out[key] = collectField(field, path);',
    '    });',
    '    return out;',
    '  }',
    '',
    '  function collectField(field, path) {',
    '    var t = (field.type || "").toLowerCase();',
    '    if (t === "bool") {',
    '      var el = document.querySelector("[data-path=\\"" + CSS.escape(path) + "\\"][data-kind=\\"bool\\"]");',
    '      return el ? el.checked : false;',
    '    }',
    '    if (t === "int" || t === "float") {',
    '      var ne = document.querySelector("[data-path=\\"" + CSS.escape(path) + "\\"][data-kind=\\"" + t + "\\"]");',
    '      if (!ne) { return field.default; }',
    '      var n = ne.value === "" ? NaN : Number(ne.value);',
    '      if (isNaN(n)) { return field.default !== undefined ? field.default : 0; }',
    '      return t === "int" ? Math.trunc(n) : n;',
    '    }',
    '    if (t === "list") {',
    '      return collectList(path, field);',
    '    }',
    '    if (t === "object" || t === "dict") {',
    '      var grp = document.querySelector("[data-path=\\"" + CSS.escape(path) + "\\"][data-kind=\\"object\\"]");',
    '      var subSchema = field.items || {};',
    '      if (!grp) { return {}; }',
    '      return collectObjectInContainer(subSchema, grp, path);',
    '    }',
    '    // string / text / 未知 / select',
    '    var se = document.querySelector("[data-path=\\"" + CSS.escape(path) + "\\"][data-kind=\\"string\\"]");',
    '    return se ? se.value : "";',
    '  }',
    '',
    '  // object 分组的收集:在给定容器内按 subSchema 逐字段',
    '  function collectObjectInContainer(subSchema, container, pathPrefix) {',
    '    var out = {};',
    '    Object.keys(subSchema).forEach(function (key) {',
    '      var field = subSchema[key];',
    '      var path = pathPrefix ? pathPrefix + "." + key : key;',
    '      if (field.invisible || field._special || (field.type || "").toLowerCase() === "file" ||',
    '          (field.type || "").toLowerCase() === "template_list" || field.editor_mode || field.editor_language) {',
    '        // placeholder 的只读值也带上',
    '        var ph = container.querySelector(".field[data-path=\\"" + CSS.escape(path) + "\\"] input");',
    '        out[key] = ph && ph.value !== "" ? ph.value : field.default;',
    '        return;',
    '      }',
    '      out[key] = collectFieldIn(field, path, container);',
    '    });',
    '    return out;',
    '  }',
    '',
    '  // collectField 的限定容器版本:用 data-path 精确定位(路径在分组内唯一)',
    '  function collectFieldIn(field, path, container) {',
    '    var t = (field.type || "").toLowerCase();',
    '    var esc = CSS.escape(path);',
    '    if (t === "bool") {',
    '      var el = container.querySelector("[data-path=\\"" + esc + "\\"][data-kind=\\"bool\\"]");',
    '      return el ? el.checked : false;',
    '    }',
    '    if (t === "int" || t === "float") {',
    '      var ne = container.querySelector("[data-path=\\"" + esc + "\\"][data-kind=\\"" + t + "\\"]");',
    '      if (!ne) { return field.default; }',
    '      var n = ne.value === "" ? NaN : Number(ne.value);',
    '      if (isNaN(n)) { return field.default !== undefined ? field.default : 0; }',
    '      return t === "int" ? Math.trunc(n) : n;',
    '    }',
    '    if (t === "list") {',
    '      var listEl = container.querySelector(".ctrl-list[data-path=\\"" + esc + "\\"]");',
    '      return listEl ? collectListEl(listEl, field) : [];',
    '    }',
    '    if (t === "object" || t === "dict") {',
    '      var grp = container.querySelector(".ctrl-object[data-path=\\"" + esc + "\\"]");',
    '      var subSchema = field.items || {};',
    '      if (!grp) { return {}; }',
    '      return collectObjectInContainer(subSchema, grp, path);',
    '    }',
    '    var se = container.querySelector("[data-path=\\"" + esc + "\\"][data-kind=\\"string\\"]");',
    '    return se ? se.value : "";',
    '  }',
    '',
    '  function collectList(path, field) {',
    '    var listEl = document.querySelector(".ctrl-list[data-path=\\"" + CSS.escape(path) + "\\"]");',
    '    return listEl ? collectListEl(listEl, field) : [];',
    '  }',
    '',
    '  function collectListEl(listEl, field) {',
    '    var complex = listEl.getAttribute("data-complex") === "1";',
    '    var itemT = listEl.getAttribute("data-item-type") || "string";',
    '    var out = [];',
    '    var items = listEl.querySelectorAll(":scope > .list-item");',
    '    items.forEach(function (itemRow) {',
    '      if (complex) {',
    '        var ta = itemRow.querySelector("textarea");',
    '        var raw = ta ? ta.value : "";',
    '        if (raw === "") { return; }',
    '        try { out.push(JSON.parse(raw)); } catch (e) { out.push(raw); }',
    '      } else if (itemT === "bool") {',
    '        var cb = itemRow.querySelector("input[type=checkbox]");',
    '        out.push(cb ? cb.checked : false);',
    '      } else if (itemT === "int" || itemT === "float") {',
    '        var ni = itemRow.querySelector("input[type=number]");',
    '        var n = ni && ni.value !== "" ? Number(ni.value) : NaN;',
    '        if (isNaN(n)) { return; }',
    '        out.push(itemT === "int" ? Math.trunc(n) : n);',
    '      } else {',
    '        // string / select',
    '        var se = itemRow.querySelector("select, input[type=text]");',
    '        out.push(se ? se.value : "");',
    '      }',
    '    });',
    '    return out;',
    '  }',
    '',
    '  // ── 错误展示 ──',
    '  function clearErrors() {',
    '    var prev = formEl.querySelectorAll(".field.error");',
    '    prev.forEach(function (el) { el.classList.remove("error"); });',
    '  }',
    '',
    '  function showErrors(errors) {',
    '    var first = null;',
    '    errors.forEach(function (er) {',
    '      // 逐级路径定位:找到 data-path 最长匹配的字段',
    '      var target = findFieldByPath(er.path);',
    '      if (target) {',
    '        target.classList.add("error");',
    '        if (!first) { first = target; }',
    '      }',
    '    });',
    '    var msgs = errors.map(function (er) { return er.path + ": " + er.message; });',
    '    showErrorBar("校验未通过(" + errors.length + " 处)\\u000a" + msgs.slice(0, 5).join("\\u000a") + (msgs.length > 5 ? "\\u2026" : ""));',
    '    if (first) { first.scrollIntoView({ behavior: "smooth", block: "center" }); }',
    '  }',
    '',
    '  function findFieldByPath(path) {',
    '    // 精确匹配,其次父级前缀(嵌套字段报全路径时,高亮最接近的祖先)',
    '    var exact = formEl.querySelector(".field[data-path=\\"" + CSS.escape(path) + "\\"]");',
    '    if (exact) { return exact; }',
    '    var parts = path.split(".");',
    '    for (var i = parts.length - 1; i > 0; i--) {',
    '      var sub = parts.slice(0, i).join(".");',
    '      var el = formEl.querySelector(".field[data-path=\\"" + CSS.escape(sub) + "\\"]");',
    '      if (el) { return el; }',
    '    }',
    '    return null;',
    '  }',
    '',
    '  function showErrorBar(msg) {',
    '    errorBar.textContent = msg;',
    '    errorBar.className = "";',
    '  }',
    '})();',
].join('\n');

// ─── 内联样式(全 --vscode-* 变量,跟随主题) ───────────────

const FORM_STYLE = [
    'body {',
    '  margin: 0; padding: 16px 24px 64px;',
    '  font-family: var(--vscode-font-family, sans-serif);',
    '  font-size: var(--vscode-font-size, 13px);',
    '  color: var(--vscode-foreground, #333);',
    '  background: var(--vscode-editor-background, #fff);',
    '}',
    '#header { display: flex; align-items: baseline; gap: 16px; margin-bottom: 12px; }',
    '#title { font-size: 1.3em; margin: 0; font-weight: 600; }',
    '.link-btn {',
    '  background: none; border: none; cursor: pointer;',
    '  color: var(--vscode-textLink-foreground, #007acc);',
    '  font-size: inherit; padding: 0;',
    '}',
    '.link-btn:hover { text-decoration: underline; }',
    '#error-bar {',
    '  background: var(--vscode-inputValidation-errorBackground, rgba(220,20,60,0.1));',
    '  border: 1px solid var(--vscode-inputValidation-errorBorder, #c30);',
    '  color: var(--vscode-errorForeground, #c30);',
    '  padding: 8px 12px; margin-bottom: 12px;',
    '  border-radius: 3px; white-space: pre-wrap;',
    '}',
    '#error-bar.hidden { display: none; }',
    '.field { padding: 10px 0; border-bottom: 1px solid var(--vscode-editorGroup-border, rgba(128,128,128,0.2)); }',
    '.field.error {',
    '  background: var(--vscode-inputValidation-errorBackground, rgba(220,20,60,0.08));',
    '  border-radius: 3px;',
    '}',
    '.field-label { display: block; font-weight: 600; margin-bottom: 4px; }',
    '.field-desc { color: var(--vscode-descriptionForeground, #888); font-size: 0.92em; margin-bottom: 6px; }',
    '.field-ctrl input[type=text], .field-ctrl input[type=number], .field-ctrl textarea, .field-ctrl select, .ctrl-text, .ctrl-number, .ctrl-textarea, .ctrl-select {',
    '  width: 100%; box-sizing: border-box;',
    '  background: var(--vscode-input-background, #fff);',
    '  color: var(--vscode-input-foreground, inherit);',
    '  border: 1px solid var(--vscode-input-border, #ccc);',
    '  padding: 4px 6px; border-radius: 2px;',
    '  font-family: var(--vscode-editor-font-family, inherit);',
    '  font-size: var(--vscode-editor-font-size, inherit);',
    '}',
    '.ctrl-textarea { resize: vertical; min-height: 2.4em; }',
    '.ctrl-bool { width: auto; }',
    '.ctrl-object { padding-left: 16px; border-left: 2px solid var(--vscode-editorGroup-border, rgba(128,128,128,0.2)); margin-top: 4px; }',
    '.ctrl-list .list-item { display: flex; gap: 6px; align-items: center; margin-bottom: 4px; }',
    '.ctrl-list .list-item > input, .ctrl-list .list-item > textarea, .ctrl-list .list-item > select { flex: 1; }',
    '.icon-btn {',
    '  background: none; border: 1px solid var(--vscode-button-border, transparent);',
    '  color: var(--vscode-errorForeground, #c30); cursor: pointer;',
    '  border-radius: 3px; padding: 2px 6px;',
    '}',
    '.ghost-btn {',
    '  background: none; border: 1px solid var(--vscode-button-border, #ccc);',
    '  color: var(--vscode-foreground, inherit); cursor: pointer;',
    '  border-radius: 2px; padding: 3px 10px; margin-top: 4px;',
    '}',
    '.slider-wrap { display: flex; align-items: center; gap: 8px; }',
    '.slider-val { color: var(--vscode-descriptionForeground, #888); min-width: 3em; }',
    '.placeholder-tip { color: var(--vscode-descriptionForeground, #888); font-size: 0.88em; margin-top: 4px; }',
    '#footer {',
    '  position: fixed; bottom: 0; left: 0; right: 0;',
    '  background: var(--vscode-editor-background, #fff);',
    '  border-top: 1px solid var(--vscode-editorGroup-border, rgba(128,128,128,0.3));',
    '  padding: 10px 24px; display: flex; align-items: center; gap: 16px;',
    '}',
    '.primary, #saveBtn {',
    '  background: var(--vscode-button-background, #007acc);',
    '  color: var(--vscode-button-foreground, #fff);',
    '  border: none; border-radius: 2px; padding: 6px 16px; cursor: pointer;',
    '  font-size: inherit;',
    '}',
    '.primary:hover, #saveBtn:hover { background: var(--vscode-button-hoverBackground, #0062a3); }',
    '#status { color: var(--vscode-descriptionForeground, #888); }',
    '#status.ok { color: var(--vscode-testing-iconPassed, #3c0); }',
].join('\n');

/** 给 TS:防止 SchemaField 类型被 tree-shake 掉(实际由 configForm.ts 用) */
export type { SchemaField };
